// articles
export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLE = 'GET_ARTICLE'
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE'
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const GET_ADMIN_ARTICLES = 'GET_ADMIN_ARTICLES'
export const UPDATE_ARTICLE_STATUS = 'UPDATE_ARTICLE_STATUS'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'

// notifications
export const ERROR_GLOBAL = 'ERROR_GLOBAL';
export const SUCCESS_GLOBAL = 'SUCCESS_GLOBAL';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'

// notifications
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

// user
export const USER_AUTH = 'USER_AUTH';
export const USER_DEAUTH = 'USER_DEAUTH';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';

// site

export const SITE_LAYOUT = 'SITE_LAYOUT';



